spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercado-livro?createDatabaseIfNotExist=true
    username: root
    password: root123
  jackson:
    default-property-inclusion: non_null

